spring:

  datasource:
    url: jdbc:mysql://localhost:3306/controle
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#swagger
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
